create table if not exists public.order_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  changed_at timestamp with time zone default now() not null,
  field text not null,
  old_value text,
  new_value text,
  source text not null check (source in ('moderator', 'sheet_sync', 'csv_import', 'system')),
  actor text
);

create index if not exists order_history_order_id_idx on public.order_history (order_id, changed_at desc);

alter table public.order_history enable row level security;

drop policy if exists "Allow public read access" on public.order_history;
drop policy if exists "Allow public insert access" on public.order_history;

create policy "Allow public read access"
  on public.order_history
  for select
  using (true);

create policy "Allow public insert access"
  on public.order_history
  for insert
  with check (true);
