-- Resolve/Ignore state for the needs_review and attention_needed flag systems. One row per
-- (order_id, flag_type), upserted in place -- not append-only. The full who/when/why audit trail
-- for resolve/ignore/re-flag actions goes through the existing order_history table instead of a
-- second log here (see lib/orderHistory.mjs).
--
-- unique(order_id, flag_type) is safe because the two systems' flag_type vocabularies never
-- overlap: missing_phone/no_items/zero_amount (needs_review) vs
-- subtotal_mismatch/stale_status/urgency_passed/duplicate_group (attention_needed).
create table if not exists public.flags (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  flag_type text not null,
  source_system text not null check (source_system in ('needs_review', 'attention_needed')),
  status text not null check (status in ('resolved', 'ignored')),
  note text,
  actor_email text not null,
  actor_name text,
  acted_at timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null,
  unique (order_id, flag_type)
);

create index if not exists flags_source_status_idx on public.flags (source_system, status);

alter table public.flags enable row level security;

drop policy if exists "Allow public read access" on public.flags;
drop policy if exists "Allow public insert access" on public.flags;
drop policy if exists "Allow public update access" on public.flags;

create policy "Allow public read access"
  on public.flags
  for select
  using (true);

create policy "Allow public insert access"
  on public.flags
  for insert
  with check (true);

create policy "Allow public update access"
  on public.flags
  for update
  using (true)
  with check (true);

notify pgrst, 'reload schema';
