-- Replaces the x1/x2/x3 confirmation_status values with a per-type attempt counter model.
-- Each order can independently accumulate no_answer/unreachable/phone_off attempts, capped at
-- 3/2/2 respectively, tracked here instead of as a single confirmation_status value. Setting
-- confirmation_status to a terminal value (confirmed_c/wa/m, cancelled, hold) wipes these rows.

create table if not exists public.contact_attempts (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  type text not null check (type in ('no_answer', 'unreachable', 'phone_off')),
  count integer not null default 0 check (count >= 0),
  first_logged_at timestamp with time zone,
  updated_at timestamp with time zone default now() not null,
  unique (order_id, type)
);

create index if not exists contact_attempts_order_id_idx on public.contact_attempts (order_id);

alter table public.contact_attempts enable row level security;

drop policy if exists "Allow public read access" on public.contact_attempts;
drop policy if exists "Allow public insert access" on public.contact_attempts;
drop policy if exists "Allow public update access" on public.contact_attempts;
drop policy if exists "Allow public delete access" on public.contact_attempts;

create policy "Allow public read access" on public.contact_attempts for select using (true);
create policy "Allow public insert access" on public.contact_attempts for insert with check (true);
create policy "Allow public update access" on public.contact_attempts for update using (true) with check (true);
create policy "Allow public delete access" on public.contact_attempts for delete using (true);

-- migrate existing x1/x2/x3 orders: each becomes a no_answer attempt of that count. No real
-- historical timestamp exists for when the marker was first set (these predate the audit trail
-- or weren't logged), so created_at is the best available stand-in for first_logged_at.
insert into public.contact_attempts (order_id, type, count, first_logged_at)
select id, 'no_answer',
  case confirmation_status when 'x1' then 1 when 'x2' then 2 when 'x3' then 3 end,
  created_at
from public.orders
where confirmation_status in ('x1', 'x2', 'x3')
on conflict (order_id, type) do nothing;

update public.orders set confirmation_status = 'pending' where confirmation_status in ('x1', 'x2', 'x3');

-- tighten confirmation_status to its new set: x1/x2/x3 are gone (replaced by contact_attempts),
-- 'hold' is added as a new terminal confirmation state (independent of urgency_type's existing
-- 'hold' value, which is unrelated and untouched)
alter table public.orders drop constraint orders_confirmation_status_check;

alter table public.orders add constraint orders_confirmation_status_check
  check (confirmation_status in ('pending', 'confirmed_c', 'confirmed_wa', 'confirmed_m', 'cancelled', 'hold'));
