do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'orders'
  ) and not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'orders_legacy'
  ) then
    alter table public.orders rename to orders_legacy;
  end if;
end $$;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  legacy_id bigint,
  order_source text not null check (order_source in ('shopify', 'social', 'otc')),
  customer_name text not null,
  phone text not null,
  address text not null,
  urgency_status text not null check (urgency_status in ('normal', 'urgent', 'hold')),
  confirmation_status text not null check (confirmation_status in ('pending', 'x1', 'x2', 'x3', 'confirmed', 'cancelled')),
  delivery_status text not null check (delivery_status in ('packaging', 'sent_to_courier', 'delivered', 'returned')),
  special_instructions text,
  cancel_return_reason text,
  happiness_score numeric,
  product_suggestions text
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  order_id bigint not null references public.orders(id) on delete cascade,
  sku text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0)
);

alter table public.orders add column if not exists legacy_id bigint;

insert into public.orders (
  legacy_id,
  created_at,
  order_source,
  customer_name,
  phone,
  address,
  urgency_status,
  confirmation_status,
  delivery_status,
  special_instructions,
  cancel_return_reason,
  happiness_score,
  product_suggestions
)
select
  id,
  created_at,
  order_source,
  customer_name,
  phone,
  address,
  urgency_status,
  confirmation_status,
  delivery_status,
  special_instructions,
  cancel_return_reason,
  happiness_score,
  product_suggestions
from public.orders_legacy
where exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'orders_legacy')
on conflict do nothing;

insert into public.order_items (order_id, sku, product_name, quantity, unit_price)
select o.id, l.sku, l.product_name, l.quantity, l.unit_price
from public.orders_legacy l
join public.orders o on o.legacy_id = l.id
where exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'orders_legacy')
on conflict do nothing;

alter table public.orders drop column if exists legacy_id;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Allow public read access" on public.orders;
drop policy if exists "Allow public insert access" on public.orders;
drop policy if exists "Allow public update access" on public.orders;
drop policy if exists "Allow public read access" on public.order_items;
drop policy if exists "Allow public insert access" on public.order_items;
drop policy if exists "Allow public update access" on public.order_items;

create policy "Allow public read access"
  on public.orders
  for select
  using (true);

create policy "Allow public insert access"
  on public.orders
  for insert
  with check (true);

create policy "Allow public update access"
  on public.orders
  for update
  using (true)
  with check (true);

create policy "Allow public read access"
  on public.order_items
  for select
  using (true);

create policy "Allow public insert access"
  on public.order_items
  for insert
  with check (true);

create policy "Allow public update access"
  on public.order_items
  for update
  using (true)
  with check (true);
